### ISSUE TITLE
Fusee.Test.Render.Desktop dies on the build service

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#157]
Calling into OpenTK seems to crash the tests on the build service.

> The active test run was aborted. Reason: Test host process crashed : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at OpenTK.Graphics.OpenGL.GL.BlendColor(Single, Single, Single, Single)
at OpenTK.Graphics.OpenGL.GL.BlendColor(System.Drawing.Color)
at Fusee.Engine.Imp.Graphics.Desktop.RenderContextImp.SetRenderState(Fusee.Engine.Common.RenderState, UInt32)
at Fusee.Engine.Core.RenderContext.SetRenderState(Fusee.Engine.Core.RenderStateSet)
at Fusee.Engine.Core.RenderContext.SetShaderEffect(Fusee.Engine.Core.ShaderEffect)
at Fusee.Engine.Core.SceneRendererForward.SetContext(Fusee.Engine.Core.RenderContext)
at Fusee.Engine.Core.SceneRendererForward.Render(Fusee.Engine.Core.RenderContext)
at Fusee.Examples.GeometryEditing.Core.GeometryEditing.RenderAFrame()
at Fusee.Engine.Core.RenderCanvas.b__31_2(System.Object, Fusee.Engine.Common.RenderEventArgs)
at Fusee.Engine.Imp.Graphics.Desktop.RenderCanvasImpBase.DoRender()
at Fusee.Engine.Imp.Graphics.Desktop.RenderCanvasImp.ShootCurrentFrame(Int32, Int32)
at Fusee.Test.Render.Desktop.Program.Main(System.String)
at Fusee.Test.Render.Desktop.RenderTests.GeometryEditingTest()

**Comment by ASPePeX** [comment]
I have an example that executes on the build service: https://github.com/ASPePeX/OpenTKTest/blob/1ea0f2df3f2fac678f952c8cf1dc99e6ea9a26eb/Test2/Program.cs

BUT, it does not render the image when running on the build service.

**Comment by ASPePeX** [comment]
It works if I carry an `opengl32.dll` with a mesa software rasterizer along (https://github.com/pal1000/mesa-dist-win/releases).

**Comment by RedImp1470** [comment]
See #504
See #535

**Comment by wrestledBearOnce** [comment]
> It works if I carry an `opengl32.dll` with a mesa software rasterizer along (https://github.com/pal1000/mesa-dist-win/releases).

I think this is the solution here:

https://github.com/FUSEEProjectTeam/Fusee/pull/535/commits/26c735d01558f460fe264066bf9b67add9e55705

Perhaps we can close this issue?
