### ISSUE TITLE
Mac Compatibility

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#386]
Current builds (0.11.1) crash with the following error:

```
Starting player ...

02.12.2021 14:00:38, [Info] [Player.cs] [Run():174] Fusee test scene. Use 'fusee player <filename/Uri>' to view .fus/.fuz files or Fusee .dlls.
 
02.12.2021 14:00:41, [Error] [RenderContext.cs] [CreateShaderProgram():1101] Error while compiling shader
 
Unhandled exception. System.Exception: Error while compiling shader
---> System.ApplicationException: ERROR: 0:1: '' :  version '300' is not supported
ERROR: 0:1: '' : syntax error: #version
ERROR: 0:2: '' :  #version required and missing.
 
   at Fusee.Engine.Imp.Graphics.Desktop.RenderContextImp.CreateShaderProgram(String vs, String ps, String gs) in /_/src/Engine/Imp/Graphics/Desktop/RenderContextImp.cs:line 581
   at Fusee.Engine.Core.RenderContext.CreateShaderProgram(Effect ef, Boolean renderForward) in /_/src/Engine/Core/RenderContext.cs:line 1081
   --- End of inner exception stack trace ---
   at Fusee.Engine.Core.RenderContext.CreateShaderProgram(Effect ef, Boolean renderForward) in /_/src/Engine/Core/RenderContext.cs:line 1102
   at Fusee.Engine.Core.SceneRendererForward.InitState() in /_/src/Engine/Core/SceneRendererForward.cs:line 755
   at Fusee.Engine.Core.SceneRendererForward.Render(RenderContext rc) in /_/src/Engine/Core/SceneRendererForward.cs:line 281
   at Fusee.Engine.Player.Core.Player.RenderAFrame() in D:\a\Fusee\Fusee\src\Engine\Player\Core\Player.cs:line 212
   at Fusee.Engine.Core.RenderCanvas.<InitApp>b__36_3(Object <p0>, RenderEventArgs <p1>) in /_/src/Engine/Core/RenderCanvas.cs:line 217
   at Fusee.Engine.Imp.Graphics.Desktop.RenderCanvasGameWindow.OnRenderFrame(FrameEventArgs args) in /_/src/Engine/Imp/Graphics/Desktop/RenderCanvasImp.cs:line 665
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Fusee.Tools.CmdLine.Verbs.Player.Run() in /_/src/Tools/CmdLine/Verbs/Player.cs:line 247
   at Fusee.Tools.CmdLine.Program.<>c.<Main>b__0_2(Player player) in /_/src/Tools/CmdLine/Program.cs:line 23
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Fusee.Tools.CmdLine.Program.Main(String[] args) in /_/src/Tools/CmdLine/Program.cs:line 12
Abort trap: 6
```

**Comment by wrestledBearOnce** [comment]
There is either: `300 es` or `330 (core)`. 

`300` without any addition is automatically parsed as `300 core` which is non existent, hence the compile error.

As usually some compiler are more relaxed than others 😉 

Fix: Change `300` to `300 es` or--where needed--to `330`

**Comment by griestopf** [comment]
Buy a Mac

**Comment by ASPePeX** [comment]
PR #493 fixed the Blender plugin to work on MacOS.

Release 0.12.1 updates all shaders to "version 330 core" an thereby breaks Android and Blazor. We urgently need some sort of way to provide correct shaders by platform (see #498)

Fusee.Tools.CmdLine works mostly. "fusee install" and "fusee publish -p desktop" doesn't work (publish desktop deploys a windows executable). "fusee publish -p web" works but uses a nasty hack to deploy the correct shader version.

**Comment by griestopf** [comment]
Tests on a 2018 MacBook Pro (Intel) resulted in awkward screen flickering wich even persisted a reboot.
