### ISSUE TITLE
RenderTests somtimes dies on CI

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#692]
Every once in a while RenderTests just falls over and can't read the fonts file. My wild guess ist that we open it writable and since the tests run simultanious it trips.

```
Unhandled exception. System.IO.IOException: The process cannot access the file 'D:\a\Fusee\Fusee\bin\Release\Tests\Render\Desktop\net7.0\Assets\Lato-Black.ttf' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at Fusee.Base.Imp.Desktop.FileAssetProvider.GetStream(String id) in /_/src/Base/Imp/Desktop/FileAssetProvider.cs:line 135
   at Fusee.Base.Common.StreamAssetProvider.GetAsset(String id, Type type) in /_/src/Base/Common/StreamAssetProvider.cs:line 59
   at Fusee.Base.Core.AssetStorage.GetAsset[T](String id) in /_/src/Base/Core/AssetStorage.cs:line 182
   at Fusee.Examples.ThreeDFont.Core.ThreeDFont.Init() in D:\a\Fusee\Fusee\Examples\Complete\ThreeDFont\Core\ThreeDFont.cs:line 37
   at Fusee.Engine.Core.RenderCanvas.<InitApp>b__39_2(Object <p0>, InitEventArgs <p1>) in /_/src/Engine/Core/RenderCanvas.cs:line 196
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by ASPePeX** [comment]
Possibly fixed in 7fd71fd0d9a69144e09ca0f53327b496e76a76c2
